modLoader = "javafml"
loaderVersion = "[2,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId = "citadel"
version = "2.7.0"
displayName = "Citadel"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "logo.png"
credits = "AlexThe666"
authors = "AlexThe666"
description = '''
A library mod required for some of AlexThe666's mods.
'''
[[mixins]]
config = "citadel.mixins.json"
[[dependencies.citadel]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,21.2)"
ordering = "NONE"
side = "BOTH"
[[dependencies.citadel]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
[[accessTransformers]]
## The 'resources' directory represents the root output directory of the resources
file = "META-INF/accesstransformer.cfg"